{ config, lib, pkgs, ... }:

let
  inherit (lib) mkEnableOption mkIf mkOption types;
  cfg = config.chase;
  ops = import ../lib/operations.nix { inherit lib; };
  bindings = cfg.bindings.gcloud;

  # Every Google API's rules, one file each, generated by chase-generate
  # gcloud (../internal/generate/gcloud) from Discovery and the protos
  # (../docs/gcloud.md). Which a session carries is decided at launch
  # (internal/apps/gcloud): a tier's, and a project's additions and
  # removals, with every API's guarded operations beneath them all.
  known = lib.attrNames (builtins.fromJSON (builtins.readFile ./gcloud/index.json));

  enabled = lib.filterAttrs (_: t: !t.bare && t.apps.gcloud.enable) cfg.tiers;
in
{
  options.chase.bindings.gcloud.package = mkOption {
    type = types.package;
    default = pkgs.google-cloud-sdk;
    defaultText = lib.literalExpression "pkgs.google-cloud-sdk";
    description = ''
      The gcloud a session gets. The consumer's to choose: Google ships it
      weekly.
    '';
  };

  options.chase.tiers = mkOption {
    type = types.attrsOf (types.submodule ({ config, ... }: {
      options.apps.gcloud = ops.appOptions config // {
        enable = mkEnableOption ''
          Google Cloud in this tier, as the service account a project binds
          in its envelope: what Google's API descriptions call a read goes
          straight through, and the rest is answered as `writes`, `guarded`
          and `unmatched` say. Only for a tier that takes envelopes: there is
          never a Google account of the machine's'';
        apis = mkOption {
          type = types.listOf (types.strMatching "[A-Za-z0-9_-]+");
          default = [ ];
          example = [ "bigquery" "storage" ];
          description = ''
            The Google APIs a session carries, by Discovery name, unless its
            project adds or removes one. A request to any other is unmatched.
          '';
        };
      };
    }));
  };

  config = {
    assertions = lib.concatLists (lib.mapAttrsToList (name: tier: [
      {
        assertion = !tier.apps.gcloud.enable || tier.envelope;
        message = "chase.tiers.${name}.apps.gcloud is enabled, but the tier takes no envelope: a Google credential is only ever a project's.";
      }
      {
        assertion = lib.all (a: lib.elem a known) tier.apps.gcloud.apis;
        message = "chase.tiers.${name}.apps.gcloud.apis names no Google API: ${toString (lib.subtractLists known tier.apps.gcloud.apis)}.";
      }
    ]) cfg.tiers);

    containers = lib.mapAttrs' (name: tier: lib.nameValuePair "agent-${name}" (mkIf tier.apps.gcloud.enable {
      config.environment = {
        systemPackages = [ bindings.package ];
        variables = {
          CLOUDSDK_CONFIG = "/run/user/${toString cfg.uid}/gcloud";
          CLOUDSDK_COMPONENT_MANAGER_DISABLE_UPDATE_CHECK = "1";
        };
      };
    })) cfg.tiers;

    # The session's route, key and first token are made at launch, and its
    # renewer started and stopped (internal/apps/gcloud).
    chase.internal.config = mkIf (enabled != { }) {
      envelope.gcloud = {
        tiers = lib.mapAttrs (_: tier: ops.settings tier.apps.gcloud // { inherit (tier.apps.gcloud) apis; }) enabled;
        catalogue = "${./gcloud}";
        inherit (ops) every;
        inherit (cfg) placeholder;
        runtimeDir = "/run/user/${toString cfg.uid}";
        systemctl = "${config.systemd.package}/bin/systemctl";
      };
    };
    chase.internal.projectApps = mkIf (enabled != { }) { gcloud = { }; };
  };
}
