{ config, lib, pkgs, ... }:

let
  inherit (lib) mkEnableOption mkIf mkOption types;
  cfg = config.chase;
  ops = import ../lib/operations.nix { inherit lib; };
  bindings = cfg.bindings.gcloud;

  # Every Google API's rules, one file each, generated by
  # ../scripts/gcloud.sh from Discovery and the protos (../docs/gcloud.md).
  # Which a session carries is decided at launch: a tier's, and a project's
  # additions and removals.
  apis = ./gcloud/apis;
  known = lib.attrNames (builtins.fromJSON (builtins.readFile ./gcloud/index.json));

  # Every API's guarded operations, whichever a session carries: a request
  # to an API it does not carry is unmatched, but never one of these, and a
  # carried API's "*" never decides another's "*:verb" among them. Named,
  # not categorised: a category is an API the session carries.
  floor = pkgs.runCommand "chase-gcloud-floor.json" { nativeBuildInputs = [ pkgs.jq ]; } ''
    jq -c -s '[.[][] | select(.operation.class == "guarded") | .operation |= del(.description, .category)]' ${apis}/*.json > $out
  '';

  enabled = lib.filterAttrs (_: t: !t.bare && t.apps.gcloud.enable) cfg.tiers;

  tiers = pkgs.writeText "chase-gcloud-tiers.json" (builtins.toJSON (lib.mapAttrs (_: tier:
    ops.settings tier.apps.gcloud // { inherit (tier.apps.gcloud) apis; }) enabled));

  # Google's own error envelope, which its clients read.
  refusal = {
    contentType = "application/json";
    body = builtins.toJSON { error = { code = 403; message = "{{message}}"; status = "PERMISSION_DENIED"; }; };
  };

  prepare = pkgs.writeShellApplication {
    name = "chase-gcloud-prepare";
    runtimeInputs = with pkgs; [ jq openssl coreutils util-linux config.systemd.package ]
      ++ [ cfg.internal.gcloudRenew ];
    text = ''
      tier=$1 ws=$2 run=$3 envdir=$4
      uid=${toString cfg.uid}
      every=${lib.escapeShellArg (builtins.toJSON ops.every)}
      machine=$(basename -- "$run")
      binding=$(cat)
      die() { echo "chase: $ws: gcloud: $*" >&2; exit 1; }

      settings=$(jq -c --arg t "$tier" '.[$t] // empty' ${tiers})
      if [ -z "$settings" ]; then
        echo "chase: $ws: gcloud ignored: $tier has no gcloud" >&2
        rm -f -- "$run/secrets/gcloud"
        echo '{}'
        exit 0
      fi

      sa=$(jq -r '.serviceAccount // empty' <<< "$binding")
      [ -n "$sa" ] || die "no serviceAccount: say which service account the key is for"
      real=$run/secrets/gcloud
      jq -e 'type == "object" and .type == "service_account" and (.private_key | type) == "string"' "$real" >/dev/null 2>&1 \
        || die "the secret is not a service-account key"
      email=$(jq -r '.client_email // empty' "$real")
      [ "$email" = "$sa" ] || die "the key is for '$email', not $sa"
      project=$(jq -r '.project_id // empty' "$real")

      selected=$(jq -c --argjson s "$settings" --argjson known ${lib.escapeShellArg (builtins.toJSON known)} '
        ((.apis.add // []) + (.apis.remove // []) - $known) as $unknown
        | if $unknown != [] then error("no Google API named \($unknown | join(", "))") else . end
        | ($s.apis + (.apis.add // []) - (.apis.remove // [])) | unique' <<< "$binding") \
        || die "its APIs do not resolve"
      mapfile -t files < <(jq -r --arg d ${apis} '.[] | "\($d)/\(.).json"' <<< "$selected")
      paths=$(jq -n -c --argjson s "$settings" --argjson every "$every" --slurpfile floor ${floor} '
        def outcome($a): if $a == "ask" then {ask: true} elif $a == "refuse" then {refuse: true} else {} end;
        [inputs[]] + ($floor[0] | map(. + {floor: true}))
        | group_by([.methods, .path, .prefix])
        | map(max_by([(.floor | not), .encodedSlashes // false]) | del(.floor))
        | map(. + outcome({read: "allow", write: $s.writes, guarded: $s.guarded}[.operation.class]))
        + (if $s.unmatched == "allow" then [{methods: $every, prefix: "/"}] else [] end)
      ' "''${files[@]}" /dev/null)

      # The session's key: made once for the checkout and the service
      # account, naming it and its project, and never seen by Google. One
      # per account, so a session launched with another leaves this one's.
      mkdir -p "$envdir"
      key=$envdir/gcloud-key-$(printf '%s %s' "$email" "$project" | sha256sum | cut -c1-16).json
      exec 9> "$envdir/.gcloud-key.lock"
      flock 9
      if ! jq -e --arg e "$email" --arg p "$project" '.client_email == $e and .project_id == $p' "$key" >/dev/null 2>&1; then
        tmp=$(mktemp "$envdir/.gcloud-key.XXXXXX")
        openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 2>/dev/null \
          | jq -Rs --arg e "$email" --arg p "$project" --arg id "$(openssl rand -hex 20)" '{
              type: "service_account",
              project_id: $p,
              private_key_id: $id,
              private_key: .,
              client_email: $e,
              auth_uri: "https://accounts.google.com/o/oauth2/auth",
              token_uri: "https://oauth2.googleapis.com/token",
              universe_domain: "googleapis.com"
            }' > "$tmp"
        mv -f -- "$tmp" "$key"
      fi
      public=$(jq -r .private_key "$key" | openssl pkey -pubout)
      exec 9>&-

      # A first token before the session starts, and a renewer for as long
      # as it runs. Google refusing the key ends the launch; Google out of
      # reach does not, since the renewer keeps trying.
      rc=0
      CHASE_GCLOUD_SA=$sa chase-gcloud-renew mint "$run" >&2 || rc=$?
      case $rc in
        0) ;;
        1) echo "chase: $ws: gcloud: no token yet, Google did not answer; the renewer keeps trying" >&2 ;;
        2) die "Google refused $sa's key: was it deleted or disabled?" ;;
        3) die "the key is not $sa's" ;;
        *) die "the renewer failed ($rc)" ;;
      esac
      XDG_RUNTIME_DIR=/run/user/$uid systemctl --user start "chase-gcloud-renew@$machine.service" \
        || die "could not start chase-gcloud-renew@$machine"

      jq <<< "$paths" \
        --argjson s "$settings" --arg sa "$sa" --arg public "$public" \
        --arg token "$run/gcloud-token.json" --arg key "$key" --argjson every "$every" \
        --arg placeholder ${lib.escapeShellArg cfg.placeholder} --argjson refusal ${lib.escapeShellArg (builtins.toJSON refusal)} '
        . as $paths | {
          routes: [
            {
              name: "gcloud",
              host: "*.googleapis.com",
              upstream: "https://*.googleapis.com",
              credentialFile: $token,
              credentialJSON: {token: "access_token", expiresMillis: "expiry"},
              placeholder: $placeholder,
              sessionKey: {publicKey: $public, issuer: $sa, grants: ["oauth2.googleapis.com/token", "www.googleapis.com/oauth2/v4/token"]},
              paths: $paths,
              unmatched: (if $s.unmatched == "ask" then "ask" else "refuse" end),
              refusal: $refusal
            },
            {
              name: "gcloud-mtls",
              host: "*.mtls.googleapis.com",
              upstream: "https://*.mtls.googleapis.com",
              paths: [{methods: $every, prefix: "/", refuse: true}],
              unmatched: "refuse"
            }
          ],
          allow: ["*.googleapis.com"],
          env: {
            GOOGLE_APPLICATION_CREDENTIALS: $key,
            CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE: $key
          }
        }'
    '';
  };

  stop = pkgs.writeShellScript "chase-gcloud-stop" ''
    [ -e "/run/user/${toString cfg.uid}/chase/$1/secrets/gcloud" ] || exit 0
    XDG_RUNTIME_DIR=/run/user/${toString cfg.uid} ${config.systemd.package}/bin/systemctl --user stop "chase-gcloud-renew@$1.service"
  '';
in
{
  options.chase.bindings.gcloud.package = mkOption {
    type = types.package;
    default = pkgs.google-cloud-sdk;
    defaultText = lib.literalExpression "pkgs.google-cloud-sdk";
    description = ''
      The gcloud a session gets. The consumer's to choose: Google ships it
      weekly.
    '';
  };

  options.chase.tiers = mkOption {
    type = types.attrsOf (types.submodule ({ config, ... }: {
      options.apps.gcloud = ops.appOptions config // {
        enable = mkEnableOption ''
          Google Cloud in this tier, as the service account a project binds
          in its envelope: what Google's API descriptions call a read goes
          straight through, and the rest is answered as `writes`, `guarded`
          and `unmatched` say. Only for a tier that takes envelopes: there is
          never a Google account of the machine's'';
        apis = mkOption {
          type = types.listOf (types.strMatching "[A-Za-z0-9_-]+");
          default = [ ];
          example = [ "bigquery" "storage" ];
          description = ''
            The Google APIs a session carries, by Discovery name, unless its
            project adds or removes one. A request to any other is unmatched.
          '';
        };
      };
    }));
  };

  config = {
    assertions = lib.concatLists (lib.mapAttrsToList (name: tier: [
      {
        assertion = !tier.apps.gcloud.enable || tier.envelope;
        message = "chase.tiers.${name}.apps.gcloud is enabled, but the tier takes no envelope: a Google credential is only ever a project's.";
      }
      {
        assertion = lib.all (a: lib.elem a known) tier.apps.gcloud.apis;
        message = "chase.tiers.${name}.apps.gcloud.apis names no Google API: ${toString (lib.subtractLists known tier.apps.gcloud.apis)}.";
      }
    ]) cfg.tiers);

    containers = lib.mapAttrs' (name: tier: lib.nameValuePair "agent-${name}" (mkIf tier.apps.gcloud.enable {
      config.environment = {
        systemPackages = [ bindings.package ];
        variables = {
          CLOUDSDK_CONFIG = "/run/user/${toString cfg.uid}/gcloud";
          CLOUDSDK_COMPONENT_MANAGER_DISABLE_UPDATE_CHECK = "1";
        };
      };
    })) cfg.tiers;

    chase.internal.projectApps.gcloud = {
      prepare = lib.getExe prepare;
      stop = "${stop}";
    };
  };
}
