# GitHub's API -- REST and GraphQL at api.github.com -- and gh, which speaks
# it. git itself is ./git.nix, an app of its own that shares this one's
# credential, so a tier can answer gh's writes and git's pushes differently
# (PLAN.md, decision 18).
{ config, lib, pkgs, ... }:

let
  inherit (lib) mkEnableOption mkIf mkOption types;
  cfg = config.chase;
  ops = import ../lib/operations.nix { inherit lib; };
  host = "api.github.com";

  # EVERY OPERATION IN GITHUB'S OWN REST API DESCRIPTION, one rule each, as
  # Cloudflare's are: a read, a write or guarded, answered as the tier and the
  # app say (../lib/operations.nix). Generated by ../scripts/operations.sh
  # from a pinned commit of github/rest-api-description, with
  # ./github/exceptions.json saying where the method is wrong -- and every
  # GraphQL mutation, from a pinned commit of GitHub's GraphQL schema, which
  # frisket tells apart by the fields at the root of the request's body; a
  # query is a read. See ../docs/github.md.
  operations = builtins.fromJSON (builtins.readFile ./github/operations.json);

  # GitHub's own error shape, whose `message` gh prints: it then says why a
  # request was refused, rather than only that it failed.
  refusal = {
    contentType = "application/json";
    body = builtins.toJSON { message = "{{message}}"; };
  };

  # Whether a tier needs GitHub's credential: either app, not anonymously.
  credentialled = t: (t.apps.github.enable && !t.apps.github.anonymous)
    || (t.apps.git.enable && !t.apps.git.anonymous);
in
{
  options.chase.bindings.github.credentialFile = mkOption {
    type = types.nullOr types.path;
    default = null;
    example = "/run/secrets/gh_token";
    description = ''
      A file holding a GitHub token, alone — `gh auth token`'s. frisket reads
      it on the host and adds it to the session's requests, gh's and git's;
      nothing inside a container ever sees it.

      Declared, never reached for: chase does not know whether the consumer
      keeps its secrets in sops, in systemd credentials, or decrypts them per
      project, and an app that hardcoded one of those could not be used with
      the others.

      Null with a tier that enables github or git non-anonymously is
      refused, not quietly downgraded — an unbound credential would otherwise
      become a route with no credential, which fails later and further away.
    '';
  };

  options.chase.tiers = mkOption {
    type = types.attrsOf (types.submodule ({ config, ... }: {
      options.apps.github = ops.appOptions config // {
        enable = mkEnableOption ''
          GitHub's API in this tier, and gh: what the API's description calls
          a read goes straight through -- a GraphQL query among them -- and
          the rest, each GraphQL mutation by its field, is answered as
          `writes`, `guarded` and `unmatched` say'';
        anonymous = mkEnableOption ''
          read-only GitHub API with no credential of yours: REST reads, and
          nothing that writes. No gh, which needs a login'';
      };
    }));
  };

  config = {
    # DECLARED BUT UNBOUND IS A REFUSAL. frisket treats an empty
    # credentialFile as a legitimate route with no credential, so leaving this
    # null would not fail -- it would silently produce a route that holds
    # requests to its scope and adds nothing, and the first sign of it would
    # be a 401 from GitHub inside a session.
    assertions = [{
      assertion = cfg.bindings.github.credentialFile != null
        || !(lib.any credentialled (lib.attrValues cfg.tiers));
      message = "chase.bindings.github.credentialFile is null, but a tier enables github or git without `anonymous`. Bind a token file, or set `anonymous = true` for read-only GitHub with no credential.";
    }];

    containers = lib.mapAttrs' (name: tier: lib.nameValuePair "agent-${name}" (mkIf (tier.apps.github.enable && !tier.apps.github.anonymous) {
      config = {
        environment.systemPackages = [ pkgs.gh ];
        # gh makes no request until it thinks it is logged in.
        environment.variables = {
          GH_TOKEN = cfg.placeholder;
          GITHUB_TOKEN = cfg.placeholder;
        };
      };
    })) cfg.tiers;

    services.frisket.policies = lib.mapAttrs (name: tier: mkIf tier.apps.github.enable (
      let s = ops.settings tier.apps.github; in
      {
        # For a tier with an allowlist of names; trusted's `*` already covers it.
        allow = lib.mkAfter [ host ];
        routes.github = {
          inherit host refusal;
          upstream = "https://${host}";
          # Anonymous, intercepted with no credential, so the scope holds: a
          # token the session brings still reaches GitHub, but only to read.
          paths = ops.paths s operations;
          graphql = ops.graphql s operations;
          unmatched = ops.unmatched s;
        } // lib.optionalAttrs (!tier.apps.github.anonymous) {
          credentialFile = cfg.bindings.github.credentialFile;
          placeholder = cfg.placeholder;
        };
      })) cfg.tiers;
  };
}
