# GitHub's API -- REST and GraphQL at api.github.com -- and gh, which speaks
# it. git itself is ./git.nix, an app of its own that shares this one's
# credential, so a tier can answer gh's writes and git's pushes differently
# (PLAN.md, decision 18).
{ config, options, lib, pkgs, ... }:

let
  inherit (lib) mkEnableOption mkIf mkOption types;
  cfg = config.chase;
  ops = import ../lib/operations.nix { inherit lib; };
  apps = import ../lib/apps.nix { inherit lib; };
  machine = options.chase.apps.github;
  host = "api.github.com";

  # EVERY OPERATION IN GITHUB'S OWN REST API DESCRIPTION, one rule each, as
  # Cloudflare's are: a read, a write or guarded, answered as the tier and the
  # app say (../lib/operations.nix). Generated by chase-generate operations
  # (../internal/generate) from a pinned commit of
  # github/rest-api-description, with ./github/exceptions.json saying where
  # the method is wrong -- and every GraphQL mutation, from a pinned commit of
  # GitHub's GraphQL schema, which frisket tells apart by the fields at the
  # root of the request's body; a query is a read. See ../docs/github.md.
  operations = builtins.fromJSON (builtins.readFile ./github/operations.json);

  # GitHub's own error shape, whose `message` gh prints: it then says why a
  # request was refused, rather than only that it failed.
  refusal = {
    contentType = "application/json";
    body = builtins.toJSON { message = "{{message}}"; };
  };
in
{
  options.chase.apps.github = {
    package = mkOption {
      type = types.package;
      default = pkgs.gh;
      defaultText = lib.literalExpression "pkgs.gh";
      description = "The gh an authenticated session gets.";
    };
    credentialFile = mkOption {
      type = types.nullOr types.path;
      default = null;
      example = "/run/secrets/gh_token";
      description = ''
        A file holding a GitHub token, alone — `gh auth token`'s. frisket reads
        it on the host and adds it to an authenticated session's requests,
        gh's, and git's unless git is given its own; nothing inside a
        container ever sees it.

        Declared, never reached for: chase does not know whether the consumer
        keeps its secrets in sops, in systemd credentials, or decrypts them per
        project, and an app that hardcoded one of those could not be used with
        the others.
      '';
    };
  };

  options.chase.tiers = mkOption {
    type = types.attrsOf (types.submodule ({ config, ... }: {
      options.apps.github = ops.appOptions config // apps.overrides machine [ "package" "credentialFile" ] // {
        enable = mkEnableOption ''
          GitHub's API in this tier: what its description calls a read goes
          straight through, with no credential and no gh, unless it is
          `authenticated`'';
        authenticated = mkEnableOption ''
          GitHub's API with the credential, and gh: what the API's
          description calls a read goes straight through -- a GraphQL query
          among them -- and the rest, each GraphQL mutation by its field, is
          answered as `writes`, `guarded` and `unmatched` say'';
      };
    }));
  };

  config = {
    assertions = apps.credentialAssertions cfg.tiers "github";

    containers = lib.mapAttrs' (name: tier: lib.nameValuePair "chase-${name}" (mkIf (tier.apps.github.enable && tier.apps.github.authenticated) {
      config = {
        environment.systemPackages = [ tier.apps.github.package ];
        # gh makes no request until it thinks it is logged in.
        environment.variables = {
          GH_TOKEN = cfg.placeholder;
          GITHUB_TOKEN = cfg.placeholder;
        };
      };
    })) cfg.tiers;

    services.frisket.policies = lib.mapAttrs (name: tier: mkIf tier.apps.github.enable (
      let s = ops.settings tier.apps.github; in
      {
        # For a tier with an allowlist of names; one allowing `*` has it already.
        allow = lib.mkAfter [ host ];
        routes.github = {
          inherit host refusal;
          upstream = "https://${host}";
          # Not authenticated, intercepted with no credential, so the scope
          # holds: a token the session brings still reaches GitHub, but only
          # to read.
          paths = ops.paths s operations;
          graphql = ops.graphql s operations;
          unmatched = ops.unmatched s;
        } // lib.optionalAttrs tier.apps.github.authenticated {
          credentialFile = tier.apps.github.credentialFile;
          placeholder = cfg.placeholder;
        };
      })) cfg.tiers;
  };
}
