{ config, options, lib, pkgs, ... }:

let
  inherit (lib) mkEnableOption mkIf mkMerge mkOption types;
  cfg = config.chase;
  ops = import ../lib/operations.nix { inherit lib; };
  apps = import ../lib/apps.nix { inherit lib; };
  machine = options.chase.apps.huggingface;
  host = "huggingface.co";

  # EVERY OPERATION IN THE HUB'S OWN API DESCRIPTION, one rule each, as
  # Cloudflare's are: a read, a write or guarded, answered as the tier and the
  # app say (../lib/operations.nix). Generated by chase-generate operations
  # (../internal/generate) from the spec vendored in ./huggingface -- the Hub
  # publishes it at a URL that moves, not at a commit -- with
  # ./huggingface/exceptions.json saying which reads are writes (the ones that
  # mint a token), which writes are reads, and what the spec leaves out that
  # huggingface_hub needs. See ../docs/huggingface.md.
  operations = builtins.fromJSON (builtins.readFile ./huggingface/operations.json);

  # Where the Hub's files come from. `resolve/` answers a large file with a
  # presigned redirect to a CDN under hf.co, and Xet's content-addressed store
  # -- cas-server.xethub.hf.co and the transfers it hands out -- is there too.
  # None of them takes the token: a presigned URL carries its own signature,
  # and Xet takes a short-lived token of its own, fetched from ${host} with
  # ours. So they are allowed by name and spliced, never intercepted.
  hosts = [ host "*.hf.co" ];

  # The Hub's own error shape, which huggingface_hub reads: it then says why
  # a request was refused, rather than only that it failed.
  refusal = {
    contentType = "application/json";
    body = builtins.toJSON { error = "{{message}}"; };
  };

  # The cache, not ~/.cache/huggingface itself: the host's token is kept
  # beside these, and a session is not to have it.
  cache = [
    "${cfg.home}/.cache/huggingface/hub"
    "${cfg.home}/.cache/huggingface/xet"
  ];
in
{
  options.chase.apps.huggingface = {
    package = mkOption {
      type = types.package;
      default = pkgs.python3Packages.huggingface-hub;
      defaultText = lib.literalExpression "pkgs.python3Packages.huggingface-hub";
      description = ''
        What puts `hf` on a session's PATH. nixpkgs has no top-level package
        for it: `hf` is a console script of the huggingface-hub library, so
        the library is what is installed.
      '';
    };
    credentialFile = mkOption {
      type = types.nullOr types.path;
      default = null;
      example = "/run/secrets/hf_token";
      description = ''
        A file holding a Hugging Face access token, alone -- what `hf auth
        login` keeps in ~/.cache/huggingface/token. frisket reads it on the
        host and adds it to an authenticated session's requests to ${host};
        nothing inside a container ever sees it. A personal account, like
        GitHub's, and not a cloud account, so a tier may hold one (PLAN.md,
        decision 9, is about the second).
      '';
    };
  };

  options.chase.tiers = mkOption {
    type = types.attrsOf (types.submodule ({ config, ... }: {
      options.apps.huggingface = ops.appOptions config // apps.overrides machine [ "package" "credentialFile" ] // {
        enable = mkEnableOption ''
          the Hugging Face Hub in this tier, through `hf` and huggingface_hub,
          read-only and with no credential of yours unless it is
          `authenticated`: public models and datasets download, and what
          would ask is refused -- every write, and every read that mints a
          token, Xet's write token among them -- so a token the session
          brings of its own cannot upload either'';
        authenticated = mkEnableOption ''
          the Hub with your token: what its API description calls a read goes
          straight through, and the rest -- an upload, a new repository, a
          read that mints a token, a deletion, and anything the description
          does not name -- is answered as `writes`, `guarded` and
          `unmatched` say'';
        scope = mkOption {
          type = types.enum [ "session" "workspace" "tier" "host" ];
          default = config.caches;
          defaultText = lib.literalExpression "the tier's `caches`";
          description = ''
            Where the Hub's downloads are kept, as the tier's `caches` say
            unless said here. `session`: the session's ~/.cache, which is
            memory. `workspace` and `tier`: on the host, under
            ~/.cache/chase/huggingface. `host`: the host's own download
            cache, read-write, so a model downloaded once is there in every
            session and on the host. Not `host` for a tier that runs other
            people's code -- the host loads what is in it, and a model file
            can be code.
          '';
        };
      };
    }));
  };

  config = {
    assertions = apps.credentialAssertions cfg.tiers "huggingface";

    chase.internal.config.session.tiers = lib.mapAttrs (_: tier: {
      stores.huggingface = {
        inherit (tier.apps.huggingface) scope;
        root = "${cfg.home}/.cache/chase/huggingface";
        env = { HF_HUB_CACHE = "hub"; HF_XET_CACHE = "xet"; };
      };
    }) (lib.filterAttrs (_: t: !t.bare && t.apps.huggingface.enable && lib.elem t.apps.huggingface.scope [ "workspace" "tier" ]) cfg.tiers);

    # On the host: a bind's source must exist, and flong makes none for it.
    # The parent too, which is where the host's token is, and so the user's
    # alone.
    systemd.tmpfiles.rules = mkIf (lib.any (t: t.apps.huggingface.enable && t.apps.huggingface.scope == "host") (lib.attrValues cfg.tiers))
      ([ "d ${cfg.home}/.cache/huggingface 0700 ${cfg.user} ${toString cfg.gid} -" ]
        ++ map (p: "d ${p} 0755 ${cfg.user} ${toString cfg.gid} -") cache);

    containers = lib.mapAttrs' (name: tier: lib.nameValuePair "agent-${name}" (mkIf tier.apps.huggingface.enable {
      bindMounts = mkIf (tier.apps.huggingface.scope == "host")
        (lib.genAttrs cache (p: { hostPath = p; isReadOnly = false; }));
      config = mkMerge [
        {
          environment.systemPackages = [ tier.apps.huggingface.package ];
          # Otherwise every command opens by saying a newer huggingface_hub
          # exists, which the session can do nothing about: the version is
          # whatever the consumer's nixpkgs pins.
          environment.variables.HF_HUB_DISABLE_UPDATE_CHECK = "1";
        }
        # The caches by name, never through XDG_CACHE_HOME, which a tier
        # keeping caches points elsewhere: the host's, bound in, or the
        # session's own at the same paths. A workspace's or the tier's are
        # a store's, which names them instead.
        (mkIf (lib.elem tier.apps.huggingface.scope [ "session" "host" ]) {
          environment.variables = {
            HF_HUB_CACHE = lib.elemAt cache 0;
            HF_XET_CACHE = lib.elemAt cache 1;
          };
        })
        # huggingface_hub sends it as a bearer token to ${host}, and to
        # nothing else: the CDN and Xet take tokens of their own.
        (mkIf tier.apps.huggingface.authenticated {
          environment.variables.HF_TOKEN = cfg.placeholder;
        })
      ];
    })) cfg.tiers;

    services.frisket.policies = lib.mapAttrs (name: tier: mkIf tier.apps.huggingface.enable {
      # For a tier with an allowlist of names; one allowing `*` has it already.
      allow = lib.mkAfter hosts;
      routes.huggingface =
        let s = ops.settings tier.apps.huggingface; in
        {
          inherit host refusal;
          upstream = "https://${host}";
          # Not authenticated, intercepted with no credential, so the scope
          # holds: a token the session brings still reaches the Hub, but only
          # for the reads. Everything else is refused -- the reads that mint
          # a token among them, Xet's write token, with which a session could
          # put bytes in Xet's store with no request here at all.
          paths = ops.paths s operations;
          unmatched = ops.unmatched s;
        } // lib.optionalAttrs tier.apps.huggingface.authenticated {
          credentialFile = tier.apps.huggingface.credentialFile;
          placeholder = cfg.placeholder;
        };
    }) cfg.tiers;
  };
}
