{ config, lib, pkgs, ... }:

let
  inherit (lib) mkEnableOption mkIf mkMerge mkOption types;
  cfg = config.chase;
  ops = import ../lib/operations.nix { inherit lib; };
  bindings = cfg.bindings.huggingface;
  host = "huggingface.co";

  # EVERY OPERATION IN THE HUB'S OWN API DESCRIPTION, one rule each, as
  # Cloudflare's are: a read, a write or guarded, answered as the tier and
  # the app say (../lib/operations.nix). Generated by ../scripts/operations.sh
  # from the spec vendored in ./huggingface -- the Hub publishes it at a URL
  # that moves, not at a commit -- with ./huggingface/exceptions.json saying
  # which reads are writes (the ones that mint a token), which writes are
  # reads, and what the spec leaves out that huggingface_hub needs. See
  # ../docs/huggingface.md.
  operations = builtins.fromJSON (builtins.readFile ./huggingface/operations.json);

  # Where the Hub's files come from. `resolve/` answers a large file with a
  # presigned redirect to a CDN under hf.co, and Xet's content-addressed store
  # -- cas-server.xethub.hf.co and the transfers it hands out -- is there too.
  # None of them takes the token: a presigned URL carries its own signature,
  # and Xet takes a short-lived token of its own, fetched from ${host} with
  # ours. So they are allowed by name and spliced, never intercepted.
  hosts = [ host "*.hf.co" ];

  # The Hub's own error shape, which huggingface_hub reads: it then says why
  # a request was refused, rather than only that it failed.
  refusal = {
    contentType = "application/json";
    body = builtins.toJSON { error = "{{message}}"; };
  };

  # The cache, not ~/.cache/huggingface itself: the host's token is kept
  # beside these, and a session is not to have it.
  cache = [
    "${cfg.home}/.cache/huggingface/hub"
    "${cfg.home}/.cache/huggingface/xet"
  ];
in
{
  options.chase.bindings.huggingface = {
    package = mkOption {
      type = types.package;
      default = pkgs.python3Packages.huggingface-hub;
      defaultText = lib.literalExpression "pkgs.python3Packages.huggingface-hub";
      description = ''
        What puts `hf` on a session's PATH. nixpkgs has no top-level package
        for it: `hf` is a console script of the huggingface-hub library, so
        the library is what is installed.
      '';
    };
    credentialFile = mkOption {
      type = types.nullOr types.path;
      default = null;
      example = "/run/secrets/hf_token";
      description = ''
        A file holding a Hugging Face access token, alone -- what `hf auth
        login` keeps in ~/.cache/huggingface/token. frisket reads it on the
        host and adds it to the session's requests to ${host}; nothing inside
        a container ever sees it. A personal account, like GitHub's, and not a
        cloud account, so a tier may hold one (PLAN.md, decision 9, is about
        the second).

        Null with a tier that enables huggingface non-anonymously is refused,
        not quietly downgraded: an unbound credential would otherwise become a
        route with no credential, whose first sign is a 401 on a gated model.
      '';
    };
  };

  options.chase.tiers = mkOption {
    type = types.attrsOf (types.submodule ({ config, ... }: {
      options.apps.huggingface = ops.appOptions config // {
        enable = mkEnableOption ''
          the Hugging Face Hub in this tier, through `hf` and huggingface_hub:
          what the Hub's API description calls a read goes straight through
          with your token, and the rest -- an upload, a new repository, a
          read that mints a token, a deletion, and anything the description
          does not name -- is answered as `writes`, `guarded` and
          `unmatched` say'';
        anonymous = mkEnableOption ''
          read-only Hugging Face with no credential of yours: public models
          and datasets download, and what would ask is refused -- every
          write, and every read that mints a token, Xet's write token among
          them -- so a token the session brings of its own cannot upload
          either'';
        shared = mkEnableOption ''
          sharing the Hub's download cache with the host, read-write: a model
          downloaded once is there in every session and on the host, rather
          than downloaded again into a session's ~/.cache, which is memory.
          Not for a tier that runs other people's code -- the host loads what
          is in this cache, and a model file can be code'';
      };
    }));
  };

  config = {
    # DECLARED BUT UNBOUND IS A REFUSAL, as with github: frisket would serve
    # a null credentialFile as a route with no credential.
    assertions = [{
      assertion = bindings.credentialFile != null
        || !(lib.any (t: t.apps.huggingface.enable && !t.apps.huggingface.anonymous) (lib.attrValues cfg.tiers));
      message = "chase.bindings.huggingface.credentialFile is null, but a tier enables huggingface without `anonymous`. Bind a token file, or set `anonymous = true` for read-only Hugging Face with no credential.";
    }];

    # On the host: a bind's source must exist, and flong makes none for it.
    # The parent too, which is where the host's token is, and so the user's
    # alone.
    systemd.tmpfiles.rules = mkIf (lib.any (t: t.apps.huggingface.enable && t.apps.huggingface.shared) (lib.attrValues cfg.tiers))
      ([ "d ${cfg.home}/.cache/huggingface 0700 ${cfg.user} ${toString cfg.gid} -" ]
        ++ map (p: "d ${p} 0755 ${cfg.user} ${toString cfg.gid} -") cache);

    containers = lib.mapAttrs' (name: tier: lib.nameValuePair "agent-${name}" (mkIf tier.apps.huggingface.enable {
      bindMounts = mkIf tier.apps.huggingface.shared
        (lib.genAttrs cache (p: { hostPath = p; isReadOnly = false; }));
      config = mkMerge [
        {
          environment.systemPackages = [ bindings.package ];
          # Otherwise every command opens by saying a newer huggingface_hub
          # exists, which the session can do nothing about: the version is
          # whatever the consumer's nixpkgs pins.
          environment.variables.HF_HUB_DISABLE_UPDATE_CHECK = "1";
        }
        # huggingface_hub sends it as a bearer token to ${host}, and to
        # nothing else: the CDN and Xet take tokens of their own.
        (mkIf (!tier.apps.huggingface.anonymous) {
          environment.variables.HF_TOKEN = cfg.placeholder;
        })
      ];
    })) cfg.tiers;

    services.frisket.policies = lib.mapAttrs (name: tier: mkIf tier.apps.huggingface.enable {
      # For a tier with an allowlist of names; one allowing `*` has it already.
      allow = lib.mkAfter hosts;
      routes.huggingface =
        let s = ops.settings tier.apps.huggingface; in
        {
          inherit host refusal;
          upstream = "https://${host}";
          # Anonymous, intercepted with no credential, so the scope holds: a
          # token the session brings still reaches the Hub, but only for the
          # reads. Everything else is refused -- the reads that mint a token
          # among them, Xet's write token, with which a session could put
          # bytes in Xet's store with no request here at all.
          paths = ops.paths s operations;
          unmatched = ops.unmatched s;
        } // lib.optionalAttrs (!tier.apps.huggingface.anonymous) {
          credentialFile = bindings.credentialFile;
          placeholder = cfg.placeholder;
        };
    }) cfg.tiers;
  };
}
